# Generated by Django 3.0.6 on 2020-11-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('file_path', models.TextField()),
                ('description', models.TextField()),
                ('size_x', models.IntegerField()),
                ('size_y', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('edited', models.DateTimeField()),
            ],
        ),
    ]
