# Generated by Django 3.0.6 on 2020-11-23 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tile',
            old_name='file_path',
            new_name='file_name',
        ),
        migrations.AlterField(
            model_name='tile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 13, 54, 29, 748631, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tile',
            name='edited',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 13, 54, 29, 748631, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tile',
            name='size_x',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tile',
            name='size_y',
            field=models.IntegerField(default=1),
        ),
    ]
