# Generated by Django 3.0.6 on 2020-11-26 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('file_name', models.TextField()),
                ('description', models.TextField()),
                ('size_x', models.IntegerField(default=100)),
                ('size_y', models.IntegerField(default=100)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 46, 3, 728231, tzinfo=utc))),
                ('edited', models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 46, 3, 728231, tzinfo=utc))),
            ],
        ),
    ]
