# Generated by Django 3.0.6 on 2020-12-15 09:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='size_x',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='size_y',
        ),
        migrations.AlterField(
            model_name='tile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 9, 36, 50, 11308, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tile',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tile',
            name='edited',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 9, 36, 50, 11308, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tile',
            name='file_name',
            field=models.TextField(default=''),
        ),
    ]
